### PR TITLE
Fixes helm install failure issue in case of partial installation. 

### LINKED ISSUE #101: Hypertrace helm install fails forever if it failed once before completion
## Use Case
Better deployment experience

## Steps to reproduce
- Installed Hypertrace with single command `hypertrace.sh install` However, it failed before completion with the an error that said k8s services aren't reachable. Unfortunately, the console output has overflown and I couldn't capture the error.
- Helm list only shows hypertrace-data-services, no platform services.
- Next run of hypertrace.sh install and subsequent runs fail with the below error.

```
[INFO] installing hypertrace platform services. namespace: hypertrace, context: docker-desktop
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "ht" chart repository
...Successfully got an update from the "hypertrace" chart repository
...Successfully got an update from the "traceable" chart repository
...Successfully got an update from the "helm" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 12 charts
Downloading hypertrace-oc-collector from repo https://traceableai.jfrog.io/traceableai/helm
Downloading jaeger-to-raw-spans-converter from repo https://traceableai.jfrog.io/traceableai/helm
Downloading raw-spans-grouper from repo https://storage.googleapis.com/hypertrace-helm-charts
Downloading hypertrace-trace-enricher from repo https://traceableai.jfrog.io/traceableai/helm
Downloading hypertrace-view-generator from repo https://traceableai.jfrog.io/traceableai/helm
Downloading hypertrace-ui from repo https://traceableai.jfrog.io/traceableai/helm
Downloading hypertrace-graphql-service from repo https://traceableai.jfrog.io/traceableai/helm
Downloading attribute-service from repo https://storage.googleapis.com/hypertrace-helm-charts
Downloading gateway-service from repo https://traceableai.jfrog.io/traceableai/helm
Downloading query-service from repo https://storage.googleapis.com/hypertrace-helm-charts
Downloading entity-service from repo https://traceableai.jfrog.io/traceableai/helm
Downloading kafka-topic-creator from repo https://storage.googleapis.com/hypertrace-helm-charts
Deleting outdated charts
history.go:52: [debug] getting history for release hypertrace-platform-services
upgrade.go:121: [debug] preparing upgrade for hypertrace-platform-services
Error: UPGRADE FAILED: "hypertrace-platform-services" has no deployed releases
helm.go:84: [debug] "hypertrace-platform-services" has no deployed releases
UPGRADE FAILED
main.newUpgradeCmd.func1
	/private/tmp/helm-20200508-23207-1ycgb97/src/helm.sh/helm/cmd/helm/upgrade.go:146
github.com/spf13/cobra.(*Command).execute
	/private/tmp/helm-20200508-23207-1ycgb97/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/private/tmp/helm-20200508-23207-1ycgb97/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/private/tmp/helm-20200508-23207-1ycgb97/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/private/tmp/helm-20200508-23207-1ycgb97/src/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
	/usr/local/Cellar/go@1.13/1.13.10_1/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go@1.13/1.13.10_1/libexec/src/runtime/asm_amd64.s:1357
./hypertrace.sh: Error at line#: 48, command: helm, error code: 1

hypertrace-helm on  feature/add_ht_attributes [$!?] at ☸️  docker-desktop (hypertrace) took 16s
➜ helm list
NAME                    	NAMESPACE 	REVISION	UPDATED                             	STATUS  	CHART                         	APP VERSION
hypertrace-data-services	hypertrace	5       	2020-07-04 18:00:57.597235 -0700 PDT	deployed	hypertrace-data-services-0.1.0	0.1.0
```

This basically happens if your install failed at some point due to timeout or k8s unavailability or any reason. 

## Proposal
- can we check if we have previously deployed releases before each install?
- If there are previously deployed releases, we can just uninstall it and then install new one.

### PR DESCRIPTION
**Pull request by JBAhire**
This PR,
- Fixes #101 
- Adds `--clean` flag for installation in case issue like #101 occurs. 
- `--clean` will uninstall previously installed `data-services` as well as `platform-services` deployments if there are any before starting actual installation process.

### CODE REVIEW

**Review by laxmanchekka — APPROVED** [review]

File: kubernetes/hypertrace.sh [hunk 1]
```diff
@@ -3,6 +3,34 @@
 set -eEu -o functrace
 script=$0
 
+function clean() {
+  EXIT_CODE=0
+  kubectl get ns ${HT_KUBE_NAMESPACE} ${KUBE_FLAGS} >/dev/null 2>&1 || EXIT_CODE=$?
```
Comment (adriancole) [inline kubernetes/hypertrace.sh:8]: Maybe you can do "set +e" entering this, then revert it at the end

That way you use `$?` after running instead of manually doing EXIT_CODE

seems less cluttered..

Comment (JBAhire) [reply kubernetes/hypertrace.sh:8]: ohh! cool! will try this.
